/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as WorkLedgerRouteImport } from './routes/work/ledger'
import { Route as WorkPulseRouteImport } from './routes/work/pulse'
import { Route as WorkSentinelRouteImport } from './routes/work/sentinel'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLedgerRoute = WorkLedgerRouteImport.update({
  id: '/work/ledger',
  path: '/work/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPulseRoute = WorkPulseRouteImport.update({
  id: '/work/pulse',
  path: '/work/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSentinelRoute = WorkSentinelRouteImport.update({
  id: '/work/sentinel',
  path: '/work/sentinel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/resume': typeof ResumeRoute
  '/work/ledger': typeof WorkLedgerRoute
  '/work/pulse': typeof WorkPulseRoute
  '/work/sentinel': typeof WorkSentinelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/resume': typeof ResumeRoute
  '/work/ledger': typeof WorkLedgerRoute
  '/work/pulse': typeof WorkPulseRoute
  '/work/sentinel': typeof WorkSentinelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/resume': typeof ResumeRoute
  '/work/ledger': typeof WorkLedgerRoute
  '/work/pulse': typeof WorkPulseRoute
  '/work/sentinel': typeof WorkSentinelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/resume'
    | '/work/ledger'
    | '/work/pulse'
    | '/work/sentinel'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/resume'
    | '/work/ledger'
    | '/work/pulse'
    | '/work/sentinel'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/resume'
    | '/work/ledger'
    | '/work/pulse'
    | '/work/sentinel'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResumeRoute: typeof ResumeRoute
  WorkLedgerRoute: typeof WorkLedgerRoute
  WorkPulseRoute: typeof WorkPulseRoute
  WorkSentinelRoute: typeof WorkSentinelRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/ledger': {
      id: '/work/ledger'
      path: '/work/ledger'
      fullPath: '/work/ledger'
      preLoaderRoute: typeof WorkLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/pulse': {
      id: '/work/pulse'
      path: '/work/pulse'
      fullPath: '/work/pulse'
      preLoaderRoute: typeof WorkPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/sentinel': {
      id: '/work/sentinel'
      path: '/work/sentinel'
      fullPath: '/work/sentinel'
      preLoaderRoute: typeof WorkSentinelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResumeRoute: ResumeRoute,
  WorkLedgerRoute: WorkLedgerRoute,
  WorkPulseRoute: WorkPulseRoute,
  WorkSentinelRoute: WorkSentinelRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
